name: Publish Files
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Files
        uses: siakhooi/publish-to-repo-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
